openapi: 3.0.3
info:
  title: OpenAPI schema for template kubernetes-namespace
components:
  schemas:
    variables:
      type: object
      required:
      - namespace
      properties:
        namespace:
          title: Namespace
          type: string
          description: Name of the namespace resource.
          x-walrus-ui:
            group: Basic
            order: 1
        quota_limits_cpu:
          title: Quota Limits CPU
          type: string
          description: CPU limits quota of the namespace. e.g. 0.5, 1, 2, 4
          default: "4"
          enum:
            - '0.5'
            - '1'
            - '2'
            - '4'
          x-walrus-ui:
            group: Quota
            order: 2
        quota_limits_memory:
          title: Quota Limits Memory
          type: string
          description: Memory limits quota of the namespace. e.g. 512Mi, 2Gi, 4Gi, 8Gi
          default: "8Gi"
          enum:
            - '512Mi'
            - '2Gi'
            - '4Gi'
            - '8Gi'
          x-walrus-ui:
            group: Quota
            order: 3
        quota_requests_cpu:
          title: Quota Requests CPU
          type: string
          description: CPU requests quota of the namespace. e.g. 0.5, 1, 2, 4
          default: "2"
          enum:
            - '0.5'
            - '1'
            - '2'
            - '4'
          x-walrus-ui:
            group: Quota
            order: 4
        quota_requests_memory:
          title: Quota Requests Memory
          type: string
          description: Memory requests quota of the namespace. e.g. 512Mi, 2Gi, 4Gi, 8Gi
          default: "4Gi"
          enum:
            - '512Mi'
            - '2Gi'
            - '4Gi'
            - '8Gi'
          x-walrus-ui:
            group: Quota
            order: 5
        default_limits_cpu:
          title: Default Limits CPU
          type: string
          description: Default CPU limits of containers in the namespace. e.g. 0.05, 0.1, 0.5, 1, 2
          default: "0.1"
          enum:
            - '0.05'
            - '0.1'
            - '0.2'
            - '0.5'
          x-walrus-ui:
            group: Limits
            order: 6
        default_limits_memory:
          title: Default Limits Memory
          type: string
          description: Default memory limits of containers in the namespace. e.g. 128Mi, 256Mi, 512Mi, 1Gi
          default: "128Mi"
          enum:
            - '128Mi'
            - '256Mi'
            - '512Mi'
            - '1Gi'
          x-walrus-ui:
            group: Limits
            order: 7
        default_requests_cpu:
          title: Default Requests CPU
          type: string
          description: Default CPU requests of containers in the namespace. e.g. 0.05, 0.1, 0.5, 1, 2
          default: "0.1"
          enum:
            - '0.05'
            - '0.1'
            - '0.2'
            - '0.5'
          x-walrus-ui:
            group: Limits
            order: 8
        default_requests_memory:
          title: Default Requests Memory
          type: string
          description: Default memory requests of containers in the namespace. e.g. 128Mi, 256Mi, 512Mi, 1Gi
          default: "128Mi"
          enum:
            - '128Mi'
            - '256Mi'
            - '512Mi'
            - '1Gi'
          x-walrus-ui:
            group: Limits
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
        - Quota
        - Limits
